### ISSUE TITLE
Compact: provide canonical, standalone, and composition-safe family surfaces

### ISSUE THREAD

**Issue by yshyn-iohk** [midnightntwrk/midnight-verifiable-credentials#490]
Umbrella issue: #487
Stage: 1

## Problem / goal
Family roots include shared Compact core modules directly, and adjacent composition has shown duplicate symbols and unprefixed helpers. Establish one canonical core owner plus standalone and composition-safe public family surfaces.

## Owned scope
- Identify the canonical Compact VC/VP source owner and add executable equivalence checks for any retained facades.
- Provide thin standalone family roots and dependency-free, family-prefixed composition entrypoints.
- Compile at least two distinct families in one Layer 3 contract without duplicate declarations or helper collisions.
- Label the two-family fixture as non-authoritative compile/composition evidence until aggregate authority lands.

## Dependencies and existing authorities
- Parent roadmap: #487; follows the terminology boundary from the Stage 0 composition-decision child.
- Preserve ADR-0013 ownership (#463/#466) and existing artifact/fixture governance (#373/#374/#378).
- The aggregate authoritative decision contract is a separate Stage 3 child.

## Acceptance criteria
- [ ] Exactly one Compact core owns canonical VC/VP semantics; retained facades are generated or equivalence-tested.
- [ ] Standalone entrypoints compile independently through public surfaces.
- [ ] Two families compile together with shared dependencies included once and no unprefixed symbol collisions.
- [ ] Mutation/equivalence tests detect semantic drift across facades and entrypoints.
- [ ] Documentation explicitly limits this fixture to non-authoritative composition evidence.

## Definition of done
A focused PR lands the public surfaces, compile fixture, equivalence/negative tests, docs, and current-head CI/review evidence.

## Non-goals
Aggregate multi-credential authority, profile resolver implementation, family lifecycle migrations, protocol adapters, or production credential products.

## Validation / evidence
Run focused Compact compile/equivalence suites, two-family clean-consumer compilation, managed-artifact drift checks, `npm run verify`, and report circuit/artifact size changes.

## AC / DoD matrix

| Acceptance / completion boundary | Required evidence |
| --- | --- |
| Owned acceptance criteria | Every checkbox above is satisfied by focused tests and reviewable artifacts. |
| Definition of done | A focused PR closes only this child, passes current-head validation/CI/review gates, and does not claim umbrella completion. |

**Comment by yshyn-iohk** [comment]
Completed by the vc-core Compact cleanup, particularly PRs #559 and #565: one canonical source owner, explicit standalone/composition exports, direct compilation, and clean-consumer composition checks are retained.
